In [3]:
import openpyxl 
import os
import pandas as pd

In [4]:
data = openpyxl.load_workbook(r"C:\Users\jambo\OneDrive\documents\02. BEBE รอบ 2 (01-20).xlsx")
data_ws = data.sheetnames
all_data = data[data_ws[0]]
df = pd.read_excel(r"C:\Users\jambo\OneDrive\documents\02. BEBE รอบ 2 (01-20).xlsx", header=4, index_col=False, dtype=object)

In [ ]:

os.chdir(r"C:\Users\jambo\OneDrive\เดสก์ท็อป\Workspaces\my-work-python-script\project_bebephone\data")
collection = 1
#separate all files
for i in df.columns[5:]:
    print(i)
    bebecode = df['Bebe code']
    productcode = df['Product code#2']
    id_shop = df[df[i] != 0][i]
    frames = [bebecode, productcode, id_shop]
    new_df = pd.concat(frames, axis=1)
    new_df = new_df.dropna()
    new__wb = openpyxl.Workbook()
    new__wb.save(f"{i}.xlsx")

    
    with pd.ExcelWriter(f"{i}.xlsx", mode="a",if_sheet_exists="overlay", engine="openpyxl") as excel:
        new_df.to_excel(excel, index=False, sheet_name=f"{i}")
    load_new_wb = openpyxl.load_workbook(f"{i}.xlsx", data_only=True)
    sheet_ws = load_new_wb.sheetnames
    if 'Sheet' in sheet_ws:
        load_new_wb.remove(load_new_wb['Sheet'])
    sheet = load_new_wb[sheet_ws[1]]
    sheet.cell(row=1, column=4).value = "Block 90"
    sheet.cell(row=1, column=5).value = "Block 117"
    sheet.cell(row=1, column=6).value = "Block 56"
    sheet.cell(row=1, column=7).value = "ชุดที่"
    for row in range(2, sheet.max_row+1):
        sheet.cell(row=row, column=4).value = f'''=CEILING(C{row},5)'''
        sheet.cell(row=row, column=5).value = f'''=CEILING(C{row},9)'''
        sheet.cell(row=row, column=6).value = f'''=CEILING(C{row},4)'''
        sheet.cell(row=row, column=7).value = collection
        if row % 53 == 0:
            collection += 1
    collection = 1
    load_new_wb.save(f"{i}.xlsx")

     Bebe code Product code#2 1832
0        48797  BBP2250010903    6
1        48822  8854430010527    2
2        48833  BBP4430023352    4
3        48844  BBP4430023348   32
4        48855  BBP1170020929    3
...        ...            ...  ...
4328    993685  BBP1150022521    3
4329    994375  BBP2270010809    7
4334    996446  BBP1150020105    4
4336    998310  BBP1170021206   10
4338    999295  BBP1150021895    5

[1501 rows x 3 columns]